### PR TITLE
Updates from klte-common

### PR DESCRIPTION
**Pull request by github-cygwin**

### CODE REVIEW

**Comment by github-cygwin** [comment]
This also fixes hires video output afaics (from my YouTube testing) 

Corinna

**Comment by IonKiwi** [comment]
nice

**Comment by github-cygwin** [comment]
Unfortunately Camera2 suddenly fails to connect to the camera when trying to take a video

I'm *really* tired of the shitty camera server behaviour.  Either Snap works as desired (except for the occassional hang when trying to flash and panorama mode not working for no apparent reason), or Camera2 works as desired, but never both, and never completely.

**Comment by github-cygwin** [comment]
The real bummer is that most of the time mm-qcamera-daemon crashes or is the hanging part, but that's the proprietary code so I have no idea how to fix this

**Pull request closed without merging**
